### ISSUE TITLE
トーナメントの参加人数を表示させたい

### ISSUE THREAD

**Issue by jueve** [kenkoooo/atcoder-tournament#1]
トーナメントにエントリーしている人の数を表示したいなと思っています。

**Comment by kenkoooo** [comment]
これは豆知識なんですけど、
resolved #1 
みたいなのをプルリクに書いておくとマージされた時に自動的に閉じてくれるらしいですよ。

**Comment by jueve** [comment]
えっそんなのあるんですか…初めて知りました。ありがとうございます。
